version: '3.8'

services:
  sentiment-analysis:
    build: .
    container_name: sentiment-mlops
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=production
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  scheduler:
    build: .
    container_name: sentiment-scheduler
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
    command: ["python", "scripts/scheduler.py"]
    restart: unless-stopped
    depends_on:
      - sentiment-analysis

volumes:
  ml_data:
  ml_models:
  ml_logs:
